"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const path=require("node:path");const{pathToFileURL}=require("node:url");
const root=path.resolve(__dirname,"..");const workerUrl=pathToFileURL(path.join(root,"go-hub-factory-mcp-worker.mjs")).href;
const workContext={workId:"WORK-OBSERVER-MCP",checkpointId:"CP-OBSERVER-MCP"};
async function load(tag){return import(`${workerUrl}?observer-mcp=${tag}-${Date.now()}`)}
test("Observer evidence service fails closed when Durable Object binding is unavailable",async()=>{const m=await load("missing");assert.equal(typeof m.createObserverEvidenceService,"function");const response=await m.createObserverEvidenceService({factoryEyeNamespace:null}).latest({workContext});assert.equal(response.status,503);assert.deepEqual(await response.json(),{code:"FACTORY_EYE_UNAVAILABLE"})});
test("Observer evidence service exposes latest sanitized packet read-only",async()=>{const m=await load("latest");const namespace={getByName(name){assert.equal(name,"ergasterion-factory-eye-v1");return{async latest(){return{ok:true,session:{sessionId:"session-1",active:true},latest:{page_title:"Edit product",fields:[{label:"Name",safe_value_or_state:"Lost Era"}],optional_screenshot_ref:"shot:1"}}}}}};const response=await m.createObserverEvidenceService({factoryEyeNamespace:namespace}).latest({workContext});assert.equal(response.status,200);const body=await response.json();assert.equal(body.latest.page_title,"Edit product");assert.equal(body.latest.fields[0].safe_value_or_state,"Lost Era");assert.equal(body.latest.optional_screenshot_ref,"shot:1")});
test("Observer latest forwards WorkContext through the MCP observer seam",async()=>{const m=await load("context");const namespace={getByName(){return{async latest(input){assert.deepEqual(input,{workContext});return{ok:true,session:{sessionId:"session-1",active:true},latest:{page_title:"Edit product"}}}}}};const response=await m.createObserverEvidenceService({factoryEyeNamespace:namespace}).latest({workContext});assert.equal(response.status,200);assert.equal((await response.json()).latest.page_title,"Edit product")});
test("Observer evidence service can return stored screenshot evidence by ref",async()=>{const m=await load("shot");const namespace={getByName(){return{async screenshot({screenshotRef}){assert.equal(screenshotRef,"shot:1");return{ok:true,screenshot:{ref:"shot:1",dataUrl:"data:image/jpeg;base64,AA==",pageFingerprint:"obsfp:abc12345"}}}}}};const response=await m.createObserverEvidenceService({factoryEyeNamespace:namespace}).screenshot({screenshotRef:"shot:1"});assert.equal(response.status,200);const body=await response.json();assert.equal(body.screenshot.ref,"shot:1");assert.equal(body.screenshot.dataUrl,"data:image/jpeg;base64,AA==")});

test("Observer evidence service uses Durable Object fetch transport when available",async()=>{const m=await load("fetch-transport");const calls=[];const namespace={getByName(name){assert.equal(name,"ergasterion-factory-eye-v1");return{async fetch(request){const url=new URL(request.url);calls.push(url.pathname);return new Response(JSON.stringify({ok:false,code:"SESSION_INACTIVE"}),{status:200,headers:{"content-type":"application/json"}})}}}};const response=await m.createObserverEvidenceService({factoryEyeNamespace:namespace}).latest({workContext});assert.equal(response.status,403);assert.deepEqual(await response.json(),{code:"SESSION_INACTIVE"});assert.deepEqual(calls,["/latest"])});
